/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-23-2008
 * 
 * XDoclet definition:
 * @struts.form name="listenvoipForm"
 */
public class ListenvoipForm extends ActionForm {
	
	
private List listeordre;
	
	private String ordre;
	private String hidden;
	
	
	
	public List getListeordre() {
			return listeordre;
		}	
		
		public void setListeordre(List listeordre) {
			this.listeordre= listeordre;
		}

		
		
		

	public String getOrdre() {
			return ordre;
		}

		public void setOrdre(String ordre) {
			this.ordre= ordre;
		}
	
		public String getHidden() {
			return hidden;
		}

		public void setHidden(String hidden) {
			this.hidden= hidden;
		}
	
	
	
	
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}