/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import java.util.List;

/** 
 * MyEclipse Struts
 * Creation date: 07-09-2008
 * 
 * XDoclet definition:
 * @struts.form name="menuForm"
 */
public class MenuForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** magasin property */
	private String magasin;
	private List listMagasin;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the magasin.
	 * @return String
	 */
	public String getMagasin() {
		return magasin;
	}

	/** 
	 * Set the magasin.
	 * @param magasin The magasin to set
	 */
	public void setMagasin(String magasin) {
		this.magasin = magasin;
	}
	
	public List getListMagasin() {
		return listMagasin;
	}
	
	
	public void setListMagasin(List listMagasin) {
		this.listMagasin = listMagasin;
	}
	
	
}