/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 11-14-2008
 * 
 * XDoclet definition:
 * 
 * @struts.form name="parametre1Form"
 */
public class Parametre1Form extends ActionForm {

	public void reset(ActionMapping mapping, HttpServletRequest request) {

		// this.setActeur("");
		/*
		 * this.setMagaberaki(false); this.setMagaregh(false);
		 * this.setMagasmar(false);
		 */
	}

	private boolean approbateur;

	private boolean magaberaki;

	// private boolean magasmar;

	// private boolean magaregh;

	private boolean superviseur_compte;

	private boolean superviseur_cds;

	private boolean magablida;

	private boolean magaconst;

	private boolean magaoran;

	private boolean admin;

	private boolean superdist;

	private boolean supereport;

	private boolean superpre;

	private boolean superpost;

	private boolean tresor;
	private boolean charge;
	private boolean sales;
	private boolean corporate;
	private boolean stockcontrol;
	private boolean edition;
	private boolean admincds;
	private boolean admindist;
	private boolean adminsrtdvrs;
	private boolean adminwrhs;
	private boolean adminfrns;
	private boolean adminprtnr;
	private boolean adminartcl;
	private boolean recepaccwithoi;

	private String acteur;
	private String hidden;
	private String hiddenTest;

	private String code;
	private String libelle;
	private List listacteur;
	private String region;
	private List listregion;
	private String activer;
	private String type;
	private String categorie;
	private String taille;
	private String writcode2;
	private String writcode1;
	private String writcod;
	private String writlib;
	private String writparam;
	private boolean coordinateur;
	private Integer consommation;
	private String cds;
	private String distributeur;
	private List listdist;
	// private List listcds;
	private List warehouselist;
	private String warehouse;
	private List cdslist;
	private List listprofil_user;

	private String profil;
	private String whs;
	
	
	
	public boolean getRecepaccwithoi() {
		return recepaccwithoi;
	}

	public void setRecepaccwithoi(boolean recepaccwithoi) {
		this.recepaccwithoi = recepaccwithoi;
	}
	
	
	public boolean getAdminartcl() {
		return adminartcl;
	}

	public void setAdminartcl(boolean adminartcl) {
		this.adminartcl = adminartcl;
	}
	
	public boolean getAdminprtnr() {
		return adminprtnr;
	}

	public void setAdminprtnr(boolean adminprtnr) {
		this.adminprtnr = adminprtnr;
	}
	
	
	public boolean getAdminfrns() {
		return adminfrns;
	}

	public void setAdminfrns(boolean adminfrns) {
		this.adminfrns = adminfrns;
	}
	
	
	public boolean getAdminwrhs() {
		return adminwrhs;
	}

	public void setAdminwrhs(boolean adminwrhs) {
		this.adminwrhs = adminwrhs;
	}
	
	
	public boolean getAdminsrtdvrs() {
		return adminsrtdvrs;
	}

	public void setAdminsrtdvrs(boolean adminsrtdvrs) {
		this.adminsrtdvrs = adminsrtdvrs;
	}
	
	public boolean getAdmindist() {
		return admindist;
	}

	public void setAdmindist(boolean admindist) {
		this.admindist = admindist;
	}
	
	public boolean getAdmincds() {
		return admincds;
	}

	public void setAdmincds(boolean admincds) {
		this.admincds = admincds;
	}

	public boolean getApprobateur() {
		return approbateur;
	}

	public void setApprobateur(boolean approbateur) {
		this.approbateur = approbateur;
	}

	public String getWhs() {
		return whs;
	}

	public void setWhs(String whs) {
		this.whs = whs;
	}

	public String getProfil() {
		return profil;
	}

	public void setProfil(String profil) {
		this.profil = profil;
	}

	public boolean getStockcontrol() {
		return stockcontrol;
	}

	public void setStockcontrol(boolean stockcontrol) {
		this.stockcontrol = stockcontrol;
	}

	public boolean getEdition() {
		return edition;
	}

	public void setEdition(boolean edition) {
		this.edition = edition;
	}

	public List getListprofil_user() {
		return listprofil_user;
	}

	public void setListprofil_user(List listprofil_user) {
		this.listprofil_user = listprofil_user;
	}

	public List getCdslist() {
		return cdslist;
	}

	public void setCdslist(List cdslist) {
		this.cdslist = cdslist;
	}

	public void setWarehouse(String warehouse) {
		this.warehouse = warehouse;
	}

	public String getWarehouse() {
		return warehouse;
	}

	public List getWarehouselist() {
		return warehouselist;
	}

	public void setWarehouselist(List warehouselist) {
		this.warehouselist = warehouselist;
	}

	public List getListdist() {
		return listdist;
	}

	public void setListdist(List listdist) {
		this.listdist = listdist;
	}

	public String getDistributeur() {
		return distributeur;
	}

	public void setDistributeur(String distributeur) {
		this.distributeur = distributeur;
	}

	public String getCds() {
		return cds;
	}

	public void setCds(String cds) {
		this.cds = cds;
	}

	public boolean getCoordinateur() {
		return coordinateur;
	}

	public void setCoordinateur(boolean coordinateur) {
		this.coordinateur = coordinateur;
	}

	public Integer getConsommation() {
		return consommation;
	}

	public void setConsommation(Integer consommation) {
		this.consommation = consommation;
	}

	public String getWritparam() {
		return writparam;
	}

	public void setWritparam(String writparam) {
		this.writparam = writparam;
	}

	public String getWritlib() {
		return writlib;
	}

	public void setWritlib(String writlib) {
		this.writlib = writlib;
	}

	public String getWritcod() {
		return writcod;
	}

	public void setWritcod(String writcod) {
		this.writcod = writcod;
	}

	public String getWritcode2() {
		return writcode2;
	}

	public void setWritcode2(String writcode2) {
		this.writcode2 = writcode2;
	}

	public String getWritcode1() {
		return writcode1;
	}

	public void setWritcode1(String writcode1) {
		this.writcode1 = writcode1;
	}

	public String getTaille() {
		return taille;
	}

	public void setTaille(String taille) {
		this.taille = taille;
	}

	public String getCategorie() {
		return categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getActiver() {
		return activer;
	}

	public void setActiver(String activer) {
		this.activer = activer;
	}

	public List getListregion() {
		return listregion;
	}

	public void setListregion(List listregion) {
		this.listregion = listregion;
	}

	public String getRegion() {
		return region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getLibelle() {
		return libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public List getListacteur() {
		return listacteur;
	}

	public void setListacteur(List listacteur) {
		this.listacteur = listacteur;
	}

	public boolean getCorporate() {
		return corporate;
	}

	public void setCorporate(boolean corporate) {
		this.corporate = corporate;
	}

	public boolean getSales() {
		return sales;
	}

	public void setSales(boolean sales) {
		this.sales = sales;
	}

	public boolean getCharge() {
		return charge;
	}

	public void setCharge(boolean charge) {
		this.charge = charge;
	}

	public boolean getTresor() {
		return tresor;
	}

	public void setTresor(boolean tresor) {
		this.tresor = tresor;
	}

	public String getHiddenTest() {
		return hiddenTest;
	}

	public void setHiddenTest(String hiddenTest) {
		this.hiddenTest = hiddenTest;
	}

	public String getActeur() {
		return acteur;
	}

	public void setActeur(String acteur) {
		this.acteur = acteur;
	}

	public String getHidden() {
		return hidden;
	}

	public void setHidden(String hidden) {
		this.hidden = hidden;
	}

	public boolean getMagaberaki() {
		return magaberaki;
	}

	public void setMagaberaki(boolean magaberaki) {
		this.magaberaki = magaberaki;
	}

	public void setSuperviseur_compte(boolean superviseur_compte) {
		this.superviseur_compte = superviseur_compte;
	}

	public boolean getSuperviseur_compte() {
		return superviseur_compte;
	}

	public void setSuperviseur_cds(boolean superviseur_cds) {
		this.superviseur_cds = superviseur_cds;
	}

	public boolean getSuperviseur_cds() {
		return superviseur_cds;
	}

	public void setMagablida(boolean magablida) {
		this.magablida = magablida;
	}

	public boolean getMagablida() {
		return magablida;
	}

	public void setMagaconst(boolean magaconst) {
		this.magaconst = magaconst;
	}

	public boolean getMagaconst() {
		return magaconst;
	}

	public void setMagaoran(boolean magaoran) {
		this.magaoran = magaoran;
	}

	public boolean getMagaoran() {
		return magaconst;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	public boolean getAdmin() {
		return admin;
	}

	public void setSupereport(boolean supereport) {
		this.supereport = supereport;
	}

	public boolean getSupereport() {
		return supereport;
	}

	public void setSuperdist(boolean superdist) {
		this.superdist = superdist;
	}

	public boolean getSuperdist() {
		return superdist;
	}

	public void setSuperpre(boolean superpre) {
		this.superpre = superpre;
	}

	public boolean getSuperpre() {
		return superpre;
	}

	public void setSuperpost(boolean superpost) {
		this.superpost = superpost;
	}

	public boolean getSuperpost() {
		return superpost;
	}
	
	
	private Collection  lisTypeId = new ArrayList();
	public Collection getLisTypeId() {
		return lisTypeId;
	}

	public void setLisTypeId(Collection lisTypeId) {
		this.lisTypeId = lisTypeId;
	}

	public Collection getLisTypeLib() {
		return lisTypeLib;
	}

	public void setLisTypeLib(Collection lisTypeLib) {
		this.lisTypeLib = lisTypeLib;
	}

	private Collection  lisTypeLib = new ArrayList(); 

}







