/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;



import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.servlet.http.HttpServletRequest;


public class RecepForm extends ActionForm {
	
	
	private String test;
	private String hidden;
	private String hiddenTest;
	private String essay;

	
private String sup;

private String transaction;

	private String type ;

	
	
	private String article;

	private String ref;
	private String magas;
	
	private Long ND = new Long(0) ;
	private Long NF = new Long(0) ;

	private String profil;

	private String note;
	
	private String fournisseur;

	private String PO;
	
	 private List nomFournisseur;
	 private List  nomArticle;
	 private List  nomProfil;
	 
	 private Recep recep = new Recep() ;
	 private List recepList;
	 private List listmagasin;
	 
	 public String getTransaction() {
			return transaction;
			}
		 
			
		public void setTransaction(String transaction) {
		            this.transaction = transaction;
			}
		
		 public String getHiddenTest() {
				return hiddenTest;
				}
			 
				
		public void setHiddenTest(String hiddenTest) {
			            this.hiddenTest = hiddenTest;
				}
			
		
	   

	 

	 public String getTest() {
			return test;
			}
		 
			
		public void setTest(String test) {
		            this.test = test;
			}
		
		 public String getEssay() {
				return essay;
				}
			 
				
			public void setEssay(String essay) {
			            this.essay = essay;
				}
	   

	
	public String getArticle() {
		return article;
	}
	
	
	public String getMagas() {
		return magas;
	}
	
	public void setArticle(String article) {
		this.article = article;
	}
	
	public void setMagas(String magas) {
		this.magas = magas;
	}

	/** 
	 * Returns the ref.
	 * @return String
	 */
	public String getRef() {
		return ref;
	}

	/** 
	 * Set the ref.
	 * @param ref The ref to set
	 */
	public void setRef(String ref) {
		this.ref = ref;
	}

	
	public Long getND() {
		return ND;
	}

	
	public void setND(Long ND) {
		this.ND = ND;
	}

	
	public Long getNF() {
		return NF;
	}


	public void setNF(Long NF) {
		this.NF = NF;
	}

	
	public String getProfil() {
		return profil;
	}

	
public void setProfil(String profil) {
		this.profil = profil;
	}

	
	public String getNote() {
		return note;
	}

	
	public void setNote(String note) {
		this.note = note;
	}

	
	public String getFournisseur() {
		return fournisseur;
	}

	
	public void setFournisseur(String fournisseur) {
		this.fournisseur = fournisseur;
	}


	public String getPO() {
		return PO;
	}

	
	public void setPO(String PO) {
		this.PO = PO;
	}
	
	
	public List getListmagasin() {
		return listmagasin;
	}	
	
	public void setListmagasin(List listmagasin) {
		this.listmagasin = listmagasin;
	}	
	
	public List getNomFournisseur() {
		return nomFournisseur;
	}	
	
	public void setNomFournisseur(List nomFournisseur) {
		this.nomFournisseur = nomFournisseur;
	}	
	
	public List getNomArticle() {
		return nomArticle;
	}	
	
	public void setNomArticle(List nomArticle) {
		this.nomArticle = nomArticle;
	}	
	
	public List getNomProfil() {
		return nomProfil;
	}	
	
	public void setNomProfil(List nomProfil) {
		this.nomProfil = nomProfil;
	}	
	
	
	public String getType() {
		return type;
	}

	
	public void setType(String type) {
		this.type = type;
	}
	
	public List getRecepList() {
		return recepList;
	}	
	
	public void setRecepList(List recepList) {
		this.recepList = recepList;
	}
	
	public Recep getRecep() {
		return recep;
	}

	
	public void setRecep(Recep recep) {
		this.recep = recep;
	}

	public String getSup() {
		return sup;
	}

	/** 
	 * Set the NF.
	 * @param NF The NF to set
	 */
	public void setSup(String sup) {
		this.sup = sup;
	}
	
	
	public String getHidden() {
		return hidden;
	}

	
	public void setHidden(String hidden) {
		this.hidden = hidden;
	}
	
	
	
	
	public void reset(ActionMapping mapping, 
			  HttpServletRequest request) {
		
		
		




ref="";
note="";
PO="";
fournisseur="";



  


}
	
	
}