/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;


public class RechercheForm extends ActionForm {
	
	
	private String nrec;
	private String fournisseur;
	private List nomFournisseur;
	private String warehouse;
	private List nomWarehouse;
	private String dat_rec_du;
	private String dat_rec_au;
	private String hidden;
	private String PQ;
	private String packaging;
	private String HLR;
	private String profil;
	private String article;
	private List nomArticle;
	private List nomProfil;
	private String position;
	private String type;
	private String sdu;
	private String sau;
	private String code_art;
	private String result;
	
	private String debut;
	private String fin;
	
	 
	private String transaction;
	private List typeTrans;
	private String responsable;
	private List nomResp;
	
	private List resultat;
	private List listajouter;
	
	private List listarticle;
	private List listprof;
    private String hiddenTest;

private String code;
private String act_id;
private String rng_id;
private String rng_pere;
private String act_pere;
private String note;
private String heur1;
private String heur2;
private String dispatch_tabs;

private String destination;
private List listdestination ;

public String getDispatch_tabs() {
	return dispatch_tabs;
}

public void setDispatch_tabs(String dispatch_tabs) {
	this.dispatch_tabs = dispatch_tabs;
}

public String getDestination() {
	return destination;
}

public void setDestination(String destination) {
	this.destination = destination;
}

public List getListdestination() {
	return listdestination;
}

public void setListdestination(List listdestination) {
	this.listdestination = listdestination;
}


public String getHeur1() {
	return heur1;
}

public void setHeur1(String heur1) {
	this.heur1 = heur1;
}
public String getHeur2() {
	return heur2;
}

public void setHeur2(String heur2) {
	this.heur2 = heur2;
}
public String getNote() {
	return note;
}

public void setNote(String note) {
	this.note = note;
}
	
public String getRng_id() {
	return rng_id;
}

public void setRng_id(String rng_id) {
	this.rng_id = rng_id;
}



public String getAct_id() {
	return act_id;
}

public void setAct_id(String act_id) {
	this.act_id = act_id;
}


public String getAct_pere() {
	return act_pere;
}

public void setAct_pere(String act_pere) {
	this.act_pere = act_pere;
}


public String getRng_pere() {
	return rng_pere;
}

public void setRng_pere(String rng_pere) {
	this.rng_pere = rng_pere;
}

public String getCode() {
	return code;
}

public void setCode(String code) {
	this.code = code;
}
	
	public String getHiddenTest() {
		return hiddenTest;
	}

	public void setHiddenTest(String hiddenTest) {
		this.hiddenTest = hiddenTest;
	}
	
	
	
	
	
	public List getListarticle() {
		return listarticle;
	}

	public void setListarticle(List listarticle) {
		this.listarticle = listarticle;
	}
	
	
	public List getListprof() {
		return listprof;
	}

	public void setListprof(List listprof) {
		this.listprof = listprof;
	}
	
	

	
	public List getListajouter() {
		return listajouter;
	}	
	
	public void setListajouter(List listajouter) {
		this.listajouter = listajouter;
	}
	
	public String getDebut() {
		return debut;
	}

	public void setDebut(String debut) {
		this.debut = debut;
	}
	
	
	public String getFin() {
		return fin;
	}

	public void setFin(String fin) {
		this.fin = fin;
	}
	
	public void setNrec(String nrec) {
		this.nrec = nrec;
	}
	
	public String getNrec() {
		return nrec;
	}
	
	public void setResult(String result) {
		this.result = result;
	}
	
	public String getResult() {
		return result;
	}

	public void setFournisseur(String fournisseur) {
		
		this.fournisseur = fournisseur;
	}
	
	public String getFournisseur() {
		return fournisseur;
	}
	
	public List getNomFournisseur() {
		return nomFournisseur;
	}	
	
	public void setNomFournisseur(List nomFournisseur) {
		this.nomFournisseur = nomFournisseur;
	}	
	
 public void setWarehouse(String warehouse) {
		
		this.warehouse = warehouse;
	}
	
	public String getWarehouse() {
		return warehouse;
	}
	
	public List getNomWarehouse() {
		return nomWarehouse;
	}	
	
	public void setNomWarehouse(List nomWarehouse) {
		this.nomWarehouse = nomWarehouse;
	}	
	
public void setDat_rec_du(String dat_rec_du) {
		
		this.dat_rec_du = dat_rec_du;
	}
	
	public String getDat_rec_du() {
		return dat_rec_du;
	}
	
public void setDat_rec_au(String dat_rec_au) {
		
		this.dat_rec_au = dat_rec_au;
	}
	
	public String getDat_rec_au() {
		return dat_rec_au;
	}	
	
 public void setHidden(String hidden) {
		
		this.hidden = hidden;
	}
	
	public String getHidden() {
		return hidden;
	}
	
	public List getResultat() {
		return resultat;
	}

	public void setResultat(List resultat) {
		this.resultat = resultat;
	}
	
	/*	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	public String getDest() {
		return dest;
	}

	public void setDest(String dest) {
		this.dest = dest;
	}
	
	public String getWhs() {
		return whs;
	}

	public void setWhs(String whs) {
		this.whs = whs;
	}
	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}
	
	public String getResp() {
		return resp;
	}

	public void setResp(String resp) {
		this.resp = resp;
	}*/
	
	
	
	public List getTypeTrans() {
		return typeTrans;
	}	
	
	public void setTypeTrans(List typeTrans) {
		this.typeTrans = typeTrans;
	}
	
	public String getTransaction() {
		return transaction;
	}

	public void setTransaction(String transaction) {
		this.transaction = transaction;
	}
	
	public String getResponsable() {
		return responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}
	
	
	public List getNomResp() {
		return nomResp;
	}	
	
	public void setNomResp(List nomResp) {
		this.nomResp = nomResp;
	}
	
	public String getPQ() {
		return PQ;
	}

	public void setPQ(String PQ) {
		this.PQ = PQ;
	}
	
	public String getPackaging() {
		return packaging;
	}

	public void setPackaging(String packaging) {
		this.packaging = packaging;
	}
	public String getHLR() {
		return HLR;
	}

	public void setHLR(String HLR) {
		this.HLR = HLR;
	}
	
	public List getNomArticle() {
		return nomArticle;
	}	
	
	public void setNomArticle(List nomArticle) {
		this.nomArticle = nomArticle;
	}	
	
	public List getNomProfil() {
		return nomProfil;
	}	
	
	public void setNomProfil(List nomProfil) {
		this.nomProfil = nomProfil;
	}	
	
	public String getArticle() {
		return article;
	}

	public void setArticle(String article) {
		this.article = article;
	}
	public String getProfil() {
		return profil;
	}

	public void setProfil(String profil) {
		this.profil = profil;
	}
	
	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}
	

	
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	public String getSau() {
		return sau;
	}

	public void setSau(String sau) {
		this.sau = sau;
	}
	
	public String getSdu() {
		return sdu;
	}

	public void setSdu(String sdu) {
		this.sdu = sdu;
	}
	
	
	public String getCode_art() {
		return code_art;
	}

	public void setCode_art(String code_art) {
		this.code_art = code_art;
	}
}