/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import java.util.ArrayList;
import java.util.List;


public class ReintegrForm extends ActionForm {
	
	


	private List listarticle;
	private List listprof;
	private List resul;
	private List resulrang;
	private List listajouter;
	private String magasourc;
	private String parten;
	private String dat;
	private List listmaga;
	private List listmaga1;
	private List listparten;
	private String priorite;
	private String idcode;
	private String hidden;
	private String article;
	private String debut;
	private String fin;
	private String profil;
	private String transaction;
	private String note;
	private String ajouter;
	private String magadist;
	private String magasin;
	private List listmagasin;
	private List nomArticle;

private String maga;
private String doc;
private String trans;
private List listeordre;
private String ordre;


private String hiddenTest;

private String  rng_id;
private String  act_id;
private String article1;


private String position;
private String packaging;
private String PQ;
private String botton2;
private String maga_reintegr;

 
public String getMaga_reintegr() {
	return maga_reintegr;
}

public void setMaga_reintegr(String maga_reintegr) {
	this.maga_reintegr = maga_reintegr;
}


public String getBotton2() {
	return botton2;
}

public void setBotton2(String botton2) {
	this.botton2 = botton2;
}

public String getPosition() {
	return position;
}

public void setPosition(String position) {
	this.position = position;
}



public String getPackaging() {
	return packaging;
}

public void setPackaging(String packaging) {
	this.packaging = packaging;
}


public String getPQ() {
	return PQ;
}

public void setPQ(String PQ) {
	this.PQ = PQ;
}





public String getArticle1() {
	return article1;
}

public void setArticle1(String article1) {
	this.article1 = article1;
}


public String getRng_id() {
	return rng_id;
}

public void setRng_id(String rng_id) {
	this.rng_id = rng_id;
}



public String getAct_id() {
	return act_id;
}

public void setAct_id(String act_id) {
	this.act_id = act_id;
}


public String getHiddenTest() {
	return hiddenTest;
}

public void setHiddenTest(String hiddenTest) {
	this.hiddenTest= hiddenTest;
}


public String getOrdre() {
	return ordre;
}

public void setOrdre(String ordre) {
	this.ordre= ordre;
}

public List getListeordre() {
	return listeordre;
}	

public void setListeordre(List listeordre) {
	this.listeordre= listeordre;
}

public String getDoc() {
	return doc;
}

public void setDoc(String doc) {
	this.doc = doc;
}

public String getTrans() {
	return trans;
}

public void setTrans(String trans) {
	this.trans = trans;
}



public List getNomArticle() {
	return nomArticle;
}

public void setNomArticle(List nomArticle) {
	this.nomArticle = nomArticle;
}



public String getMaga() {
	return maga;
}

public void setMaga(String maga) {
	this.maga = maga;
}
	
public String getMagasin() {
	return magasin;
}

public void setMagasin(String magasin) {
	this.magasin= magasin;
}


public List getListmagasin() {
	return listmagasin;
}	

public void setListmagasin (List listmagasin) {
	this.listmagasin= listmagasin;
}	



	
	public String getAjouter() {
		return ajouter;
	}

	public void setAjouter(String ajouter) {
		this.ajouter = ajouter;
	}
	
	private List packList= new ArrayList() ;
	
	
	public List getListajouter() {
		return listajouter;
	}	
	
	public void setListajouter(List listajouter) {
		this.listajouter = listajouter;
	}
	
	public String getHidden() {
		return hidden;
	}

	public void setHidden(String hidden) {
		this.hidden = hidden;
	}
	
	
	public List getPackList() {
		return packList;
	}	
	
	public void setPackList(List packList) {
		this.packList = packList;
	}
	
	
	public String getIdcode() {
		return idcode;
	}

	public void setIdcode(String idcode) {
		this.idcode = idcode;
	}
	
	
	public String getPriorite() {
		return priorite;
	}

	public void setPriorite(String priorite) {
		this.priorite = priorite;
	}
	

	public List getListparten() {
		return listparten;
	}

	public void setListparten(List listparten) {
		this.listparten = listparten;
	}
	
	public List getResul() {
		return resul;
	}

	public void setResul(List resul) {
		this.resul= resul;
	}
	
	public List getResulrang() {
		return resulrang;
	}

	public void setResulrang(List resulrang) {
		this.resulrang = resulrang;
	}
	
	
	public List getListmaga1() {
		return listmaga1;
	}

	public void setListmaga1(List listmaga1) {
		this.listmaga1 = listmaga1;
	}
	
	
	public List getListmaga() {
		return listmaga;
	}

	public void setListmaga(List listmaga) {
		this.listmaga = listmaga;
	}
	
	
	
	public String getMagadist() {
		return magadist;
	}

	public void setMagadist(String magadist) {
		this.magadist = magadist;
	}
	
	
	public String getMagasourc() {
		return magasourc;
	}

	public void setMagasourc(String magasourc) {
		this.magasourc = magasourc;
	}
	
	
	public String getParten() {
		return parten;
	}

	public void setParten(String parten) {
		this.parten = parten;
	}
	
	
	public String getDat() {
		return dat;
	}

	public void setDat(String dat) {
		this.dat = dat;
	}
	
	public String getDebut() {
		return debut;
	}

	public void setDebut(String debut) {
		this.debut = debut;
	}
	
	
	public String getFin() {
		return fin;
	}

	public void setFin(String fin) {
		this.fin = fin;
	}
	
	public String getArticle() {
		return article;
	}

	public void setArticle(String article) {
		this.article = article;
	}
	
	

	
	public List getListarticle() {
		return listarticle;
	}

	public void setListarticle(List listarticle) {
		this.listarticle = listarticle;
	}
	
	
	public String getProfil() {
		return profil;
	}

	public void setProfil(String profil) {
		this.profil = profil;
	}
	
	
	
	public String getTransaction() {
		return transaction;
	}

	public void setTransaction(String transaction) {
		this.transaction = transaction;
	}
	
	
	
	
	public List getListprof() {
		return listprof;
	}

	public void setListprof(List listprof) {
		this.listprof = listprof;
	}
	
	
	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	
}