/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jxl.write.WritableSheet;
import jxl.write.WriteException;
import jxl.write.biff.RowsExceededException;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.RedirectingActionForward;
import org.apache.struts.actions.DispatchAction;

import com.yourcompany.struts.UtilBean.Article;
import com.yourcompany.struts.UtilBean.Rang3;
import com.yourcompany.struts.UtilClass.Connexion;
import com.yourcompany.struts.UtilClass.Helper;
import com.yourcompany.struts.form.RechercheForm;
import com.yourcompany.struts.form.TransfertForm;

 
public class AnnulerActionV2 extends DispatchAction {
	
	public ActionForward afficher(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws IOException, ServletException, SQLException, RowsExceededException, WriteException {
		RechercheForm rechercheForm = (RechercheForm) form;
		
		Connexion connexion=new Connexion();
		Connection con=connexion.createConnection(request);
		

		Statement st,st1,st2,st3,st4,st5 = null;
		ResultSet rs,rs1,rs2,rs3,rs4,rs5 = null;
		ArrayList list = new ArrayList();
		ArrayList list1 = new ArrayList();
		ArrayList listart = new ArrayList();
		ArrayList listprof = new ArrayList();
		List typeTrans= new ArrayList() ;
		List nomResp= new ArrayList() ;
		
	/*	List listart= new ArrayList() ;
		List listprof= new ArrayList() ;*/
		
		st=con.createStatement();
		st1=con.createStatement();
		st2=con.createStatement();
		st3=con.createStatement();
		
		String user= (String)request.getSession().getAttribute("username");
		System.out.println(user);
		
		rs1=st1.executeQuery("select art_art_libelle from gss_article,gss_article_type where (gss_article.art_type_id=gss_article_type.art_type_id) and (art_status='A')");
		//rs2=st2.executeQuery("select profil_libelle from gss_article_profil where profil_statut='A'");	
		//rs3=st3.executeQuery("select distinct t.trans_type||'-'||t.whs_id||'-'||t.trans_no,t.trans_date,a.act_name,nvl(d.dest_nom,'_') from gss_transaction t,gss_range r,gss_actor2 a,gss_destinataire d  where t.trans_no(+)=r.trans_no and t.trans_type(+)=r.trans_type and t.whs_id(+)=r.whs_id  and t.act_id=a.act_id and d.dest_id(+)=t.dest_id and t.trans_type not in ('ANN')and  r.rng_inactif='A' minus  select distinct t.trans_type||'-'||t.whs_id||'-'||t.trans_no,t.trans_date,a.act_name,nvl(d.dest_nom,'_') from gss_transaction t,gss_range r,gss_actor2 a,gss_destinataire d  where t.trans_no(+)=r.trans_no and t.trans_type(+)=r.trans_type and t.whs_id(+)=r.whs_id and r.rng_inactif='I' and t.act_id=a.act_id and d.dest_id(+)=t.dest_id and t.trans_type not in ('ANN')");
		rs=st.executeQuery("select trans_type_libelle from gss_transaction_type order by trans_type_libelle");
		rs2=st2.executeQuery("select act_name from gss_actor where act_status='A'");
		
		
		
		while (rs1.next())
		{
			    		    		
		String art = rs1.getString(1).trim();
		System.out.println(art);
		listart.add(art);
		    			    		
		}
		
		
		while (rs.next())
		{
			    		    		
		String type = rs.getString(1).trim();
		System.out.println(type);
		typeTrans.add(type);
		    			    		
		}
		
		while (rs2.next())
		{
			    		    		
		String nom_respons = rs2.getString(1).trim();
		System.out.println(nom_respons);
		nomResp.add(nom_respons);
		    			    		
		}
		
		
	/*	while (rs2.next())
		{
			    		    		
		String prof = rs2.getString(1).trim();
		System.out.println(prof);
		listprof.add(prof);
		    			    		
		}*/
		
		 /*   while (rs3.next())
            {
      	  
			  
			  Article art = new Article();
			  
  	       art.setCode(rs3.getString(1).trim()); 
			art.setDate(rs3.getString(2).trim());
			art.setDest(rs3.getString(4).trim());
			art.setResp(rs3.getString(3).trim());
			
			list.add(art);
			
            }*/

		  Article art = new Article();
		  
	       art.setCode(""); 
		art.setDate("");
		art.setDest("");
		art.setResp("");
		art.setAnnuler("");
		
		list.add(art);
     
//		rechercheForm.setListprof(listprof);
		//	System.out.println(listprof);	
	rechercheForm.setResultat(list) ; 
    rechercheForm.setListarticle(listart);
    rechercheForm.setTypeTrans(typeTrans);
	rechercheForm.setNomResp(nomResp);
	System.out.println(listart);
	
	rechercheForm.setArticle("");
	//rechercheForm.setProfil("");
	rechercheForm.setDebut("");
	rechercheForm.setFin("");
	rechercheForm.setNote("");
	rechercheForm.setDat_rec_au("");
	rechercheForm.setDat_rec_du("");
	rechercheForm.setType("");
	rechercheForm.setNrec("");
	rechercheForm.setTransaction("");
	rechercheForm.setResponsable("");
	
	


	    	con.close();
     
		return mapping.findForward("annuler");
}
	
	
	
	public ActionForward remplir(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws IOException, ServletException, SQLException, RowsExceededException, WriteException {
	
		RechercheForm rechercheForm = (RechercheForm) form;
		
		
		 String art=request.getParameter("art");
		  String prof=request.getParameter("prof");
		  String start=request.getParameter("start");
		  String end=request.getParameter("end");
		  String qte=request.getParameter("qte");
		  
		  String code=request.getParameter("code");
		  String rng_id=request.getParameter("rng_id");
		  String act_id=request.getParameter("act_id");
		  
		  String rng_pere=request.getParameter("rng_pere");
		  String act_pere=request.getParameter("act_pere");
		
		  
		  System.out.println(art);
		  System.out.println(prof);
		  System.out.println(start);
		  System.out.println(end);
		  System.out.println(qte);
		  
		  System.out.println(code);
		  System.out.println(rng_id);
		  System.out.println(act_id);
		  System.out.println(rng_pere);
		  System.out.println(act_pere);
		  
		 
		  
		  rechercheForm.setArticle(art);
		  rechercheForm.setProfil(prof);
		  rechercheForm.setDebut(start);
		   rechercheForm.setFin(end);
		   rechercheForm.setCode(code);
		   rechercheForm.setRng_id(rng_id);
		   rechercheForm.setAct_id(act_id);
		   rechercheForm.setAct_pere(act_pere);
		   rechercheForm.setRng_pere(rng_pere);
		
		   
		  rechercheForm.setHiddenTest("");
		
		
		return mapping.findForward("annuler");
	}
	
	public ActionForward chercher(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws IOException, ServletException, SQLException, RowsExceededException, WriteException {
		RechercheForm rechercheForm = (RechercheForm) form;
		
		
		Connexion connexion=new Connexion();
		  Connection con=connexion.createConnection(request);
		  Article art = new Article();
		  Statement st=null;
		  ResultSet rs=null;
   st=con.createStatement();
   List list = new ArrayList();
   List list1 = null;
   String set,dateDu,dateAu,four,mag,txt,txt1,txt2,requette,resp,type_trans,artc,prof,hlr,pq,pack,pos,typ,nd,nf = null;
String requete1,requete2,requete3=null;
	
	set = rechercheForm.getNrec();
	System.out.println(set);
dateDu = rechercheForm.getDat_rec_du();
	System.out.println(dateDu);
	dateAu = rechercheForm.getDat_rec_au();
	System.out.println(dateAu);		
	resp = rechercheForm.getResponsable();
	System.out.println(resp);	
	type_trans = rechercheForm.getTransaction();
	System.out.println(type_trans);
	artc = rechercheForm.getArticle();
	System.out.println(artc);
String start=rechercheForm.getDebut();
String end=rechercheForm.getFin();
System.out.println(start);
System.out.println(end);



//requete1="select distinct t.trans_type||'-'||t.whs_id||'-'||t.trans_no,t.trans_date,a.act_name,nvl(d.dest_nom,'_') from gss_transaction t,gss_range r,gss_actor2 a,gss_destinataire d,gss_article art,gss_transaction_type typ  where t.trans_no(+)=r.trans_no and t.trans_type(+)=r.trans_type and t.whs_id(+)=r.whs_id  and t.act_id=a.act_id and d.dest_id(+)=t.dest_id and t.trans_type not in ('ANN')and  r.rng_inactif='A' and t.trans_type=typ.trans_type and art.art_id=r.art_id  and   t.annuler <>'A'";
//requete2="select distinct t.trans_type||'-'||t.whs_id||'-'||t.trans_no,t.trans_date,a.act_name,nvl(d.dest_nom,'_') from gss_transaction t,gss_range r,gss_actor2 a,gss_destinataire d,gss_article art,gss_transaction_type typ  where t.trans_no(+)=r.trans_no and t.trans_type(+)=r.trans_type and t.whs_id(+)=r.whs_id and r.rng_inactif='I' and t.act_id=a.act_id and d.dest_id(+)=t.dest_id and t.trans_type not in ('ANN') and t.trans_type=typ.trans_type and art.art_id=r.art_id  and   t.annuler <>'A'";
 
requete1="SELECT distinct t.trans_type||'-'||t.whs_id||'-'||t.trans_no, t.trans_date,a.act_name,nvl(d.dest_nom,'_')  FROM ( select tr.t_r_rng_id,tr.t_r_rng_act_id,max(tr.t_r_date) as max_tr from gss_transaction_range tr,gss_range r,gss_transaction t   where tr.t_r_rng_id=r.rng_id and tr.t_r_rng_act_id=r.act_id and r.rng_inactif='A'and t.trans_no=tr.t_r_trans_no and t.trans_type=tr.t_r_trans_type and t.whs_id=tr.t_r_trans_whs and t.annuler='N' group by tr.t_r_rng_id,tr.t_r_rng_act_id ) aa,gss_transaction_range,gss_transaction t, gss_actor2 a,gss_destinataire d,gss_transaction_type typ,gss_range r    where  gss_transaction_range.t_r_rng_id=aa.t_r_rng_id and  gss_transaction_range.t_r_rng_act_id=aa.t_r_rng_act_id and  gss_transaction_range.t_r_date=max_tr  and  gss_transaction_range.t_r_trans_type=t.trans_type and  gss_transaction_range.t_r_trans_whs=t.whs_id  and  gss_transaction_range.t_r_trans_no=t.trans_no  and d.dest_id(+)=t.dest_id and t.trans_type=typ.trans_type   and  gss_transaction_range.t_r_rng_id=r.rng_id and  gss_transaction_range.t_r_rng_act_id=r.act_id and t.act_id=a.act_id";
requete2="SELECT distinct t.trans_type||'-'||t.whs_id||'-'||t.trans_no, t.trans_date,a.act_name,nvl(d.dest_nom,'_')  FROM ( select tr.t_r_rng_id,tr.t_r_rng_act_id,max(tr.t_r_date) as max_tr from gss_transaction_range tr,gss_range r,gss_transaction t   where tr.t_r_rng_id=r.rng_id and tr.t_r_rng_act_id=r.act_id and r.rng_inactif='I'and t.trans_no=tr.t_r_trans_no and t.trans_type=tr.t_r_trans_type and t.whs_id=tr.t_r_trans_whs and t.annuler='N' group by tr.t_r_rng_id,tr.t_r_rng_act_id ) aa,gss_transaction_range,gss_transaction t, gss_actor2 a,gss_destinataire d,gss_transaction_type typ,gss_range r    where  gss_transaction_range.t_r_rng_id=aa.t_r_rng_id and  gss_transaction_range.t_r_rng_act_id=aa.t_r_rng_act_id and  gss_transaction_range.t_r_date=max_tr  and  gss_transaction_range.t_r_trans_type=t.trans_type and  gss_transaction_range.t_r_trans_whs=t.whs_id  and  gss_transaction_range.t_r_trans_no=t.trans_no  and d.dest_id(+)=t.dest_id and t.trans_type=typ.trans_type   and  gss_transaction_range.t_r_rng_id=r.rng_id and  gss_transaction_range.t_r_rng_act_id=r.act_id and t.act_id=a.act_id";
if (set != "")
{
	txt = set.substring(0,3);
	System.out.println("txt="+txt);
	txt1 = set.substring(4,7);
	System.out.println("txt1="+txt1);
	txt2 = set.substring(8);
	System.out.println("txt2="+txt2);
	/*
	CallableStatement cstmt = null;
    String test;
    cstmt = con.prepareCall("{?=call LAST_TRANSACTION(?,?,?,?)}");
    cstmt.registerOutParameter(1, Types.VARCHAR);
    cstmt.registerOutParameter(5, Types.VARCHAR);
    cstmt.setString(2, txt);
    cstmt.setString(3, txt1);
    cstmt.setString(4, txt2);
    cstmt.execute();
    test= cstmt.getString(1);
    if(test.equals("true")) System.out.println("Last transation");
    else System.out.println("Not last Transaction");
    */


	
	//requete1=requete1+" and t.trans_type='"+txt+"' and t.whs_id='"+txt1+"' and t.trans_no='"+txt2+"' ";
	//requete2=requete2+" and t.trans_type='"+txt+"' and t.whs_id='"+txt1+"' and t.trans_no='"+txt2+"' ";
}	

if ((dateDu != "") && (dateAu != ""))
{
	requete1 = requete1 + " and (trunc(trans_date) BETWEEN '"+dateDu+"' AND '"+dateAu+"')";
	requete2 = requete2 + " and (trunc(trans_date) BETWEEN '"+dateDu+"' AND '"+dateAu+"')";

}

if (resp !=""){
	
	requete1 = requete1+" and (a.act_name='"+resp+"')";
	requete2 = requete2+" and (a.act_name='"+resp+"')";
}	

if (type_trans!="")
{
	requete1=requete1+" and (typ.trans_type_libelle='"+type_trans+"')";
	requete2=requete2+" and (typ.trans_type_libelle='"+type_trans+"')";
}

if (artc!="")
{
	requete1 = requete1 +" and (art.art_art_libelle = '"+artc+"')";
	requete2 = requete2 +" and (art.art_art_libelle = '"+artc+"')";
}

if ((start != "") && (end != ""))
{
	requete1 = requete1 +" and (('"+start+"' between r.rng_start and r.rng_end) or ('"+end+"' between r.rng_start and r.rng_end))";
	requete2 = requete2 +" and (('"+start+"' between r.rng_start and r.rng_end) or ('"+end+"' between r.rng_start and r.rng_end))";	
}

requete3=requete1+" minus "+requete2;
//System.out.println("requete3="+requete3);

//System.out.println("requete1="+requete1);
rs=st.executeQuery(requete3);
System.out.println("requete3="+requete3);
//rs=st.executeQuery(requete3);
//rs=st.executeQuery("select distinct  t.trans_type||'-'||t.whs_id||'-'||t.trans_no,t.trans_date,a.act_name,nvl(d.dest_nom,'_') from gss_transaction t,gss_range r,gss_actor2 a,gss_destinataire d  where   t.trans_no=r.trans_no and t.trans_type=r.trans_type and t.whs_id=r.whs_id  and r.rng_inactif='A'  and t.trans_type not in ('ANN') and t.act_id=a.act_id and d.dest_id(+)=t.dest_id   and (('"+start+"' between r.rng_start and r.rng_end) or ('"+end+"' between r.rng_start and r.rng_end))  minus   select distinct t.trans_type||'-'||t.whs_id||'-'||t.trans_no,t.trans_date,a.act_name,d.dest_nom from gss_transaction t,gss_range r,gss_actor2 a,gss_destinataire d  where   t.trans_no=r.trans_no and t.trans_type=r.trans_type and t.whs_id=r.whs_id  and r.rng_inactif='I'  and t.trans_type not in ('ANN')  and t.act_id=a.act_id and d.dest_id(+)=t.dest_id  ");
		 
/*		    while (rs.next())
            {
      	  
Article art = new Article();
			  
  	       art.setCode(rs.getString(1).trim()); 
			art.setDate(rs.getString(2).trim());
			art.setDest(rs.getString(4).trim());
			art.setResp(rs.getString(3).trim());
		//	art.setAnnuler("");
 list.add(art);
		
          }
          */
Helper h = new Helper();

String retun;
 //if there is a code transaction then we call annulTransaction, other ways call  getListAnnulTransaction
if(set!=null && set.length()>0){
retun = h.annulTransaction(set, request);
if(!retun.equals("NO"))	{
	art = new Article();
	art.setCode(set);
	list.add(art);
}
}else {
	System.out.println("Dans le else : ");
    list1 = (List) h.getListAnnulTransaction(start, end, request);
    for(int j = 0;j<list1.size(); j++){
    	art = new Article();
    	art.setCode((String)list1.get(j));
    	list.add(art);
    }
}

System.out.println("End ");
rechercheForm.setResultat(list) ;
		  
	return mapping.findForward("annuler");	
	}
	

	public ActionForward Retirer(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws IOException, ServletException, SQLException, RowsExceededException, WriteException {
		RechercheForm rechercheForm = (RechercheForm) form;
		
		
		
		return mapping.findForward("annuler");
	}
	
	
	 public String getResult(String Str)
	 {
	  return ((Str != null) ? Str=Str.trim():Str); 
	 }
	 
	 
	 public String setResult(String Str)
	 {
	  return ((Str != null) ? Str : null); 
	 }


public ActionForward valider(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response)throws IOException, ServletException, SQLException, RowsExceededException, WriteException {
	RechercheForm rechercheForm = (RechercheForm) form;
	
	Connexion connexion=new Connexion();
	  Connection con=connexion.createConnection(request);
	  
	  Statement st,st1,st4,st3,st2,st5,st6=null;
	  ResultSet rs,rs1,rs4,rs3,rs2,rs5,rs6=null;
	  int h,h1,up=0;
	  Long R2;
	  String start_rang_anuuler,end_rang_anuuler=null;
	  
	  String idpart = null,idact=null,idart,idprof,maxrng=null,res1=null,res2,start,end,tra=null,wh=null,
	  no=null,whp,pfp,arp,rp,acp,pq,statu,swap,promo,prior=null,p,t,s,r,sta2=null,end2,res3=null,P,whspac=null;
	  String max=null;String   txt=null,txt1=null,txt2=null;
	  String code_reserv_tso=null;
	  String code_reserv_sor=null;
	  String dispatch_flag="";
	  
	  st=con.createStatement();
	  st1=con.createStatement();
	  st4=con.createStatement();
	  st3=con.createStatement();
	  st2=con.createStatement();
	  st5=con.createStatement();
	  st6=con.createStatement();
	  con.setAutoCommit(false);
	  int h2;
	  
  String note=rechercheForm.getNote();
  System.out.println("note"+note);  
	  String act= (String)request.getSession().getAttribute("username");
	  System.out.println(act);
	  
	  rs3=st3.executeQuery("select ACT_ID from gss_actor where act_name='"+act+"'");
 while (rs3.next())
	     {
	                  
	      idact = rs3.getString(1).trim();
	     System.out.println(idact);
	      }
 
 

	  
String code=request.getParameter("code_art");
 System.out.println("code"+code);
 
 /*String note=request.getParameter("annuler");
 System.out.println("note"+note);*/
 
 /*
 String code=rechercheForm.getCode();
 System.out.println(code);*/
 
 
 
 
 txt = code.substring(0,3);
 System.out.println("txt="+txt);
    txt1 = code.substring(4,7);
 System.out.println("txt1="+txt1);
    txt2 = code.substring(8);
 System.out.println("txt2="+txt2);
 
 
 rs3=st3.executeQuery("select nvl(t.trans_ext_ref,'_'),nvl(t.trans_no_po,'_') from gss_transaction t where trans_type='"+txt+"' and whs_id='"+txt1+"' and trans_no='"+txt2+"' ");
 while (rs3.next())
	     {
	                  
	      code_reserv_tso = rs3.getString(1).trim();
	     System.out.println(idact);
	     
	     code_reserv_sor = rs3.getString(2).trim();
		     System.out.println(idact);
	      }
 
 
 
 
 try{ 
 
	 System.out.println("select r.rng_id,r.act_id,r.rng_id_parent,r.act_id_parent from gss_range r where r.trans_type='"+txt+"' and r.whs_id='"+txt1+"' and r.trans_no ='"+txt2+"' ");
	   //  rs=st.executeQuery("select r.rng_id,r.act_id,r.rng_id_parent,r.act_id_parent,rng_start,rng_end from gss_range r where r.trans_type='"+txt+"' and r.whs_id='"+txt1+"' and r.trans_no ='"+txt2+"' and r.rng_inactif='A' ");
	  rs=st.executeQuery("select r.rng_id,r.act_id,r.rng_id_parent,r.act_id_parent,rng_start,rng_end,rng_trans_hist from gss_range r,gss_transaction_range  tr where  r.rng_id=tr.t_r_rng_id and r.act_id=tr.t_r_rng_act_id and  r.rng_inactif='A'  and tr.t_r_trans_type='"+txt+"' and tr.t_r_trans_whs='"+txt1+"' and tr.t_r_trans_no='"+txt2+"'");
	     while (rs.next())
	     {
	         String act_id=rs.getString(2).trim();
	         String rng_id=rs.getString(1).trim();
	         System.out.println("act_id"+act_id);
	         System.out.println("rng_id"+rng_id);
	        
	         String rng_pere=rs.getString(3).trim();	
	         String act_pere=rs.getString(4).trim();
	         System.out.println("rng_pere"+rng_pere);
	         System.out.println("act_pere"+act_pere);
	         
	          start_rang_anuuler=rs.getString(5).trim();	
	          end_rang_anuuler=rs.getString(6).trim();
	          dispatch_flag = rs.getString(7);
	          if(dispatch_flag!=null) dispatch_flag=dispatch_flag.trim(); else dispatch_flag="";
	          System.out.println("dans le while");
	    if (txt.equals("REC"))
	      {
	        int i1=st1.executeUpdate("update gss_range r set  r.rng_inactif='I',r.rng_inactif_date=sysdate where r.rng_id='"+rng_id+"' and r.act_id='"+act_id+"'") ;
	      }
	      else
	      {
	    	  System.out.println("dans le while 1");
	    	//int i3=st3.executeUpdate("update gss_range r set  r.rng_inactif='A',r.rng_inactif_date='' where r.rng_id='"+rng_pere+"' and r.act_id='"+act_pere+"'");  
	    	 int i2=st2.executeUpdate("update gss_range r set  r.rng_inactif='I',r.rng_inactif_date=sysdate where r.rng_id='"+rng_id+"' and r.act_id='"+act_id+"'") ;
	      
	    	 System.out.println("dans le while 2");
	    	      rs4=st4.executeQuery("select nvl(max(rng_id),'1000000000') from gss_range where ACT_ID='"+idact+"'");
	    	      System.out.println("dans le while 3");
	    	      if (rs4.next()){
	    	          maxrng=rs4.getString(1).trim();
	    	         System.out.println(maxrng);
	    	         
	    	         R2=Long.parseLong(maxrng);
	    	         R2=R2+1;
	    	      res1=Long.toString(R2);
	    	      System.out.println(res1);
	    	         
	    	         }
	    	      
	   
	    	      
	    	       
	    	      System.out.println("dans le while 4");
	    	     
	    	  rs2=st2.executeQuery("select rng_start,rng_end,rng_id,act_id,profil_id,r.art_id,rng_pq,rng_statut,rng_tpd,trans_type,whs_id,trans_no,rng_promotion,rng_priorite,rng_packaged,rng_transfert,rng_sortie,rng_reintegration,rng_whs,rng_dist,r.rng_packaging_whs,r.rng_sortie_whs,r.rng_reintegration_whs,rng_transfert_whs, r.rng_id_parent,r.act_id_parent,r.rng_trans_hist from gss_range r where r.rng_id='"+rng_pere+"' and r.act_id='"+act_pere+"'");
	    	   
	    	
	    	     
	    	   
	    	     while (rs2.next()){
	    	      System.out.println("dans le while");
	    	      
	    	       
	    	      
	    	      start = rs2.getString(1).trim();
	    	      System.out.println("1"+start);
	    	      
	    	      end = rs2.getString(2).trim();
	    	      System.out.println("2"+end);
	    	      
	    	      rp=rs2.getString(3).trim();
	    	      System.out.println("3"+rp);
	    	      
	    	      acp=rs2.getString(4).trim();
	    	      System.out.println("4"+acp);
	    	      
	    	      pfp=getResult(rs2.getString(5));
	    	        System.out.println("5"+pfp);
	    	      
	    	      
	    	      arp=rs2.getString(6).trim();
	    	      System.out.println("6"+arp);
	    	      
	    	      
	    	     pq=getResult(rs2.getString(7));
	    	        System.out.println("7"+pq);
	    	      
	    	      statu=rs2.getString(8).trim();
	    	       System.out.println("8"+statu);
	    	      
	    	    String  tdp=getResult(rs2.getString(9));
	    	        System.out.println("9"+tdp);
	    	      
	    	         tra=getResult(rs2.getString(10));
	                  System.out.println("21"+tra);
	                  
	                  wh=getResult(rs2.getString(11));
	                  System.out.println("21"+wh);
	                  
	                  no=getResult(rs2.getString(12));
	                  System.out.println("21"+no);
	        
	    	      
	    	      promo=getResult(rs2.getString(13));
	    	        System.out.println(promo);
	    	        
                 prior=getResult(rs2.getString(14));
	    	        System.out.println(prior);
	    	      
	    	      p=rs2.getString(15).trim();
	    	      t=rs2.getString(16).trim();
	    	      s=rs2.getString(17).trim();
	    	      r=rs2.getString(18).trim();
	    	      
	    	      whp=rs2.getString(19).trim();
	    	     
	    	          String dist=getResult(rs2.getString(20));
	    	       System.out.println("20"+dist);
	    	       
	    	       
	    	       String whspack=getResult(rs2.getString(21));
	    	                  System.out.println("21"+whspack);
	    	            
	    	       String whssor=getResult(rs2.getString(22));
	    	       System.out.println("22"+whssor);
	    	             
	    	       String whsrentegr=getResult(rs2.getString(23));
	    	       System.out.println("23"+whsrentegr);
	    	       String whstransfert=getResult(rs2.getString(24));
	    	       System.out.println("24"+whstransfert);
	    	       
	    	       
	    	       String rng_pere_new=getResult(rs2.getString(25));
	    	       System.out.println("24"+whstransfert);
	    	     
	    	       String act_pere_new=getResult(rs2.getString(26));
	    	       String rng_trans_hist = getResult(rs2.getString(27));
	    	       if(tra==null) tra="";
	    	       if(wh==null) wh="";
	    	       if(no==null) no="";
	    	       if(rng_trans_hist!=null) System.out.println("rng_trans_hist 1 : "+rng_trans_hist); else rng_trans_hist="";
	    	       System.out.println("rng_trans_hist : "+rng_trans_hist);
	    	       System.out.println("24"+whstransfert);
	    	     //  int    h2 = st3.executeUpdate("insert into gss_range values ('"+res1+"','"+idact+"',decode('"+pfp+"','null',null,'"+pfp+"'),'"+arp+"','"+start_rang_anuuler+"','"+end_rang_anuuler+"','"+rng_pere+"','"+act_pere+"','A',SYSDATE,'',decode('"+pq+"','null',null,'"+pq+"'),'"+statu+"',decode('"+tra+"','null',null,'"+tra+"'),decode('"+wh+"','null',null,'"+wh+"'),decode('"+no+"','null',null,'"+no+"'),'',decode('"+tdp+"','null',null,'"+tdp+"'),decode('"+promo+"','null',null,'"+promo+"'),decode('"+prior+"','null',null,'"+prior+"'),'"+p+"','"+t+"','"+s+"','"+r+"','"+whp+"',decode('"+dist+"','null',null,'"+dist+"'),decode('"+whspack+"','null',null,'"+whspack+"'),decode('"+whssor+"','null',null,'"+whssor+"'),decode('"+whsrentegr+"','null',null,'"+whsrentegr+"'),decode('"+whstransfert+"','null',null,'"+whstransfert+"'))");
	    	       System.out.println("insert into gss_range values ('"+res1+"','"+idact+"',decode('"+pfp+"','null',null,'"+pfp+"'),'"+arp+"','"+start_rang_anuuler+"','"+end_rang_anuuler+"','"+rng_pere_new+"','"+act_pere_new+"','A',SYSDATE,'',decode('"+pq+"','null',null,'"+pq+"'),'"+statu+"','','','','',decode('"+tdp+"','null',null,'"+tdp+"'),decode('"+promo+"','null',null,'"+promo+"'),decode('"+prior+"','null',null,'"+prior+"'),'"+p+"','"+t+"','"+s+"','"+r+"','"+whp+"',decode('"+dist+"','null',null,'"+dist+"'),decode('"+whspack+"','null',null,'"+whspack+"'),decode('"+whssor+"','null',null,'"+whssor+"'),decode('"+whsrentegr+"','null',null,'"+whsrentegr+"'),decode('"+whstransfert+"','null',null,'"+whstransfert+"'))");
	    	      if((txt.equals("SOR") || txt.equals("TST")) && dispatch_flag!=null && dispatch_flag.equals("dispatché")){
	    	   h2 = st3.executeUpdate("insert into gss_range values ('"+res1+"','"+idact+"',decode('"+pfp+"','null',null,'"+pfp+"'),'"+arp+"','"+start_rang_anuuler+"','"+end_rang_anuuler+"','"+rng_pere_new+"','"+act_pere_new+"','V',SYSDATE,'',decode('"+pq+"','null',null,'"+pq+"'),'"+statu+"', '"+txt+"','"+txt1+"','"+txt2+"','"+dispatch_flag+"',   decode('"+tdp+"','null',null,'"+tdp+"'),decode('"+promo+"','null',null,'"+promo+"'),decode('"+prior+"','null',null,'"+prior+"'),'"+p+"','"+t+"','"+s+"','"+r+"','"+whp+"',decode('"+dist+"','null',null,'"+dist+"'),decode('"+whspack+"','null',null,'"+whspack+"'),decode('"+whssor+"','null',null,'"+whssor+"'),decode('"+whsrentegr+"','null',null,'"+whsrentegr+"'),decode('"+whstransfert+"','null',null,'"+whstransfert+"'))");
	    	       }else
	    	        {  System.out.println("insert into gss_range values ('"+res1+"','"+idact+"',decode('"+pfp+"','null',null,'"+pfp+"'),'"+arp+"','"+start_rang_anuuler+"','"+end_rang_anuuler+"','"+rng_pere_new+"','"+act_pere_new+"','A',SYSDATE,'',decode('"+pq+"','null',null,'"+pq+"'),'"+statu+"','"+tra+"','"+wh+"','"+no+"','"+rng_trans_hist+"',decode('"+tdp+"','null',null,'"+tdp+"'),decode('"+promo+"','null',null,'"+promo+"'),decode('"+prior+"','null',null,'"+prior+"'),'"+p+"','"+t+"','"+s+"','"+r+"','"+whp+"',decode('"+dist+"','null',null,'"+dist+"'),decode('"+whspack+"','null',null,'"+whspack+"'),decode('"+whssor+"','null',null,'"+whssor+"'),decode('"+whsrentegr+"','null',null,'"+whsrentegr+"'),decode('"+whstransfert+"','null',null,'"+whstransfert+"'))"); 
	    	    	   h2 = st3.executeUpdate("insert into gss_range values ('"+res1+"','"+idact+"',decode('"+pfp+"','null',null,'"+pfp+"'),'"+arp+"','"+start_rang_anuuler+"','"+end_rang_anuuler+"','"+rng_pere_new+"','"+act_pere_new+"','A',SYSDATE,'',decode('"+pq+"','null',null,'"+pq+"'),'"+statu+"','"+tra+"','"+wh+"','"+no+"','"+rng_trans_hist+"',decode('"+tdp+"','null',null,'"+tdp+"'),decode('"+promo+"','null',null,'"+promo+"'),decode('"+prior+"','null',null,'"+prior+"'),'"+p+"','"+t+"','"+s+"','"+r+"','"+whp+"',decode('"+dist+"','null',null,'"+dist+"'),decode('"+whspack+"','null',null,'"+whspack+"'),decode('"+whssor+"','null',null,'"+whssor+"'),decode('"+whsrentegr+"','null',null,'"+whsrentegr+"'),decode('"+whstransfert+"','null',null,'"+whstransfert+"'))");    
	    	       }
	    	       
	    	       System.out.println("insert into gss_transaction_range select t_r_trans_type, t_r_trans_whs,t_r_trans_no,"+res1+" ,'"+idact+"'code ,t_r_date from gss_transaction_range where t_r_rng_id='"+rng_id+"' and t_r_rng_act_id ='"+act_id+"'");
	      int  h3 = st4.executeUpdate("insert into gss_transaction_range select t_r_trans_type, t_r_trans_whs,t_r_trans_no,"+res1+" ,'"+idact+"'code ,t_r_date from gss_transaction_range where t_r_rng_id='"+rng_id+"' and t_r_rng_act_id ='"+act_id+"'");
	  	    
	    	     
	    	     }
	    	     
	    		  
	      }
	      }	
	     String procedure_update=null;
	         			
if ((txt.equals("TSO"))&& !(code_reserv_tso.equals("_")) ){
	
	  System.out.println("je vais mettre à jour la réservation ");
	   procedure_update = "{call UPDATE_RESRV_AFTER_ANNUL_TSO(?,?,?)}";
	   
		  CallableStatement call = con.prepareCall(procedure_update);
		  call.setString(1,txt);
		  call.setString(2,txt1);
		  call.setString(3,txt2);	  
		  //call.execute();
	
}

if ((txt.equals("SOR"))&& !(code_reserv_sor.equals("_")) ){
	
	
	  System.out.println("je vais mettre à jour la réservation ");
	 procedure_update = "{call UPDATE_RESRV_AFTER_ANNUL_SOR(?,?,?)}";
	 
	  CallableStatement call = con.prepareCall(procedure_update);
	  call.setString(1,txt);
	  call.setString(2,txt1);
	  call.setString(3,txt2);	  
	  //call.execute();
	
}


	  
	//  con.commit();
	

	     
	 		 System.out.println("update   Gss_Transaction t  set t.annuler='A'   WHERE t.trans_no='"+txt2+"' and t.trans_type='"+txt+"' and t.whs_id='"+txt1+"'") ;
	 		int i4=st4.executeUpdate("update   Gss_Transaction t  set t.annuler='A'   WHERE t.trans_no='"+txt2+"' and t.trans_type='"+txt+"' and t.whs_id='"+txt1+"'") ;

	       

//	   insérer la transaction de l'annulation dans transaction 
	  String trans_annuler =txt+"-"+txt1+"-"+txt2; 	  
	  System.out.println("insert into  gss_approbation values ('"+max+"','ANN','W00',sysdate,'"+idact+"','','','"+note+"')");
	  i4=st4.executeUpdate(" delete from   gss_approbation p where p.trans_no='"+txt2+"' and p.trans_type='"+txt+"' and p.whs_id='"+txt1+"'") ;
	  int i5=st5.executeUpdate("insert into  gss_approbation values ('"+txt2+"','"+txt+"','"+txt1+"',sysdate,'"+idact+"','','','"+note+"')");
   con.commit();
    //con.close();
	     
  }
	    
   	catch(SQLException ex){
   		System.out.println("y'a un prob ");   
   	 ex.printStackTrace();
		
	   con.rollback();
      con.close(); 
	   throw ex;
				
			}
    finally
    {
    	con.close();
    }
   	
  //  String num="ANN"+"-"+"W00"+"-"+max;
    String num =txt+"-"+txt1+"-"+txt2; 
    request.setAttribute("num", num);
    System.out.println("le num de transaction"+num);
    String typetrans="annulé";
    request.getSession().setAttribute("typetrans", typetrans);
	
   return mapping.findForward("menu");
	 	
	 	
}
public ActionForward annuler(ActionMapping mapping, ActionForm form,
		   HttpServletRequest request, HttpServletResponse response)throws IOException, ServletException, SQLException  {
		  
	RechercheForm rechercheForm = (RechercheForm) form;
	
		  ActionForward  forward = new RedirectingActionForward();
		       forward.setPath("/annuler.do?hidden=afficher");
		       return forward;
		       }

}