/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yourcompany.struts.UtilBean.Profil;
import com.yourcompany.struts.UtilClass.Connexion;
import com.yourcompany.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2009
 * 
 * XDoclet definition:
 * @struts.action path="/gestionprofil" name="loginForm" parameter="hidden" validate="true"
 * @struts.action-forward name="listprofil" path="/forms/listprofil.jsp"
 */
public class GestionprofilAction extends DispatchAction {

	public ActionForward gestionprofil(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		
		Connexion connexion=new Connexion();
		Connection con= connexion.createConnection(request);
		
      
		Statement st = null;
		ResultSet rs = null;
		st=con.createStatement();
		
		String profil_user =loginForm.getProfil();
		System.out.println(profil_user);
		String warehouse=loginForm.getWarehouse();
		System.out.println(warehouse);
		System.out.println("select p.priv_libelle from gss_privilege p,gss_profil_actor pa ,gss_profil_privillege pv where pv.profil_act_id=pa.profil_act_id and pv.priv_id=p.priv_id and pa.profil_act_libelle='"+profil_user+"'");
		rs=st.executeQuery("select p.priv_libelle from gss_privilege p,gss_profil_actor pa ,gss_profil_privillege pv where pv.profil_act_id=pa.profil_act_id and pv.priv_id=p.priv_id and pa.profil_act_libelle='"+profil_user+"'");
		
		
		 ArrayList privileg_user =new ArrayList();
		 
		
		 
		 while (rs.next())
     	{
     		Profil profil =new Profil();
     		System.out.println(rs.getString(1).trim());
     		profil.setProf(rs.getString(1).trim());
     		profil.setWhs(warehouse);
     		profil.setProfil(profil_user);
     		
     		  	   		
     		privileg_user.add(profil);
     	
     	}
		 
		 
		 request.getSession().setAttribute("privilege", privileg_user);
		
		return mapping.findForward("menu");
	}
}