/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yourcompany.struts.UtilBean.Listenvoip;
import com.yourcompany.struts.UtilBean.Ordre;
import com.yourcompany.struts.UtilBean.Profil;
import com.yourcompany.struts.UtilClass.Connexion;
import com.yourcompany.struts.form.ListenvoipForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-23-2008
 * 
 * XDoclet definition:
 * @struts.action path="/listenvoip" name="listenvoipForm" scope="request" validate="true"
 * @struts.action-forward name="envoi" path="/forms/listenvoip.jsp"
 */
public class ListenvoipAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		ListenvoipForm listenvoipForm = (ListenvoipForm) form;// TODO Auto-generated method stub
		
		
		Connexion connexion=new Connexion();
		Connection con=connexion.createConnection(request);
		
		Statement st = null;
		ResultSet rs = null;
		Integer R,R1;
		String whs=null;
		String prio=null;
		
		ArrayList list = new ArrayList();
		ArrayList priv =  new ArrayList() ;
		
		
		
		
		
		priv = (ArrayList)request.getSession().getAttribute("privilege");

		for ( int i=0;i<priv.size();i++){
			System.out.println("le i :"+i);
			Profil profi =(Profil)priv.get(i);

			if (profi.getProf().equals("AJOUTER RECEP PACKAGING")){
			 whs=profi.getWhs();
			System.out.println("whs recep packaging :"+whs);
			//request.getSession().setAttribute("werhs",whs4);
			break;}}
		
		
		request.getSession().setAttribute("warehouse1",whs);	
		

		st=con.createStatement();
		rs=st.executeQuery("select distinct gss_transaction.trans_no,gss_transaction.trans_type,gss_transaction.whs_id ,gss_transaction.trans_type|| '-' ||gss_transaction.whs_id || '-' ||gss_transaction.trans_no,gss_destinataire.dest_nom,decode(gss_range.rng_priorite, '1', 'haute', '0', 'bas', '_') PRIORITE,gss_range.rng_priorite,gss_transaction.trans_date_limite from gss_transaction,gss_range,gss_destinataire,gss_transaction_range where gss_transaction_range.t_r_trans_no=gss_range.trans_no and gss_transaction_range.t_r_trans_type=gss_range.trans_type and gss_transaction_range.t_r_trans_whs=gss_range.whs_id and gss_range.rng_inactif='A' and gss_range.rng_packaged='C' and gss_transaction_range.t_r_trans_type='PAC' and gss_range.rng_whs='"+whs+"' and gss_transaction.dest_id=gss_destinataire.dest_id and gss_transaction_range.t_r_trans_no= gss_transaction.trans_no and gss_transaction_range.t_r_trans_type=gss_transaction.trans_type and gss_transaction_range.t_r_trans_whs=gss_transaction.whs_id");
while (rs.next()){
	Listenvoip listenvoip = new Listenvoip();
	//Ordre ordre = new Ordre();
	listenvoip.setOrdre(rs.getString(4).trim());
	listenvoip.setType(rs.getString(2).trim()); 
	listenvoip.setCode(rs.getString(1).trim());
	listenvoip.setWhs(rs.getString(3).trim());
	
	String date=rs.getString(8).trim();
	System.out.println(date);
	listenvoip.setDate(rs.getString(8).trim());
	
	listenvoip.setPart(rs.getString(5).trim());
	
	//listenvoip.setPartt(rs.getString(5).trim());
	listenvoip.setPrio(rs.getString(6).trim());
	//System.out.println(rs.getString(7).trim());
		

//prio=rs.getString(7).trim();
list.add(listenvoip);

	
}

listenvoipForm.setListeordre(list);



	con.close();



return mapping.findForward("envoi"); 
	}
}