/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;



import java.io.IOException;
import java.sql.SQLException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yourcompany.struts.form.EnvoiForm;
import com.yourcompany.struts.form.ParametreForm;


import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.yourcompany.struts.UtilBean.*;
import com.yourcompany.struts.UtilClass.*;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.RedirectingActionForward;
import org.apache.struts.actions.DispatchAction;
import com.yourcompany.struts.form.EnvoiForm;
import java.util.*;


public class ParametreAction extends DispatchAction {
	
	
	public ActionForward chercher(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException,IOException, ServletException  {
		ParametreForm parametreForm = (ParametreForm) form;
		
		Connexion connexion=new Connexion();
		Connection con=connexion.createConnection(request);
		
		Statement st,st1,st2,st3,st4 = null;
		ResultSet rs,rs1,rs2,rs3,rs4 = null;
		String  acteur = null,act=null;
		int max=0;
		Boolean p1,p2,p3,p4,p5,p6,p7,p8,p9,p10=false;
		boolean trouv=false;
		
		st=con.createStatement();
		st1=con.createStatement();
st2=con.createStatement();

		
	
try{	
	rs=st.executeQuery("select gss_profil_actor.profil_act_libelle,w.whs_adresse from gss_actor,gss_droit_acces,gss_profil_actor,gss_warehouse w where gss_actor.act_id=gss_droit_acces.act_id  and gss_droit_acces.profil_act_id=gss_profil_actor.profil_act_id and w.whs_id=gss_droit_acces.whs_id and gss_actor.act_name='"+acteur+"'");
		while (rs.next()){
	   	   String profil=rs.getString(1).trim();
	   	  String  whs=rs.getString(2).trim(); 
	   	    System.out.println(profil+whs);
	   	    if ((profil.equals("MAGASINIER CENTRAL")) && (whs.equals("BERAKI")))
	   	    
	   	    {
	   	    	System.out.println("magasinier beraki");
	   	    	parametreForm.setMagaberaki(true)	;
	   	    	/*trouv=true;	
	   	    	
	   			parametreForm.setMagaregh(false);
	   			parametreForm.setMagasmar(false);
	   			parametreForm.setSuperdist(false);
	   			parametreForm.setAdmin(false);
	   			parametreForm.setMagablida(false);
	   			parametreForm.setMagaconst(false);
	   			parametreForm.setMagaoran(false);
	   			parametreForm.setSupereport(false);
	   			parametreForm.setSuperpre(false);
	   			parametreForm.setSuperpost(false)	;*/
	   	    }	    
	   	    
	   	 if ((profil.equals("MAGASINIER CENTRAL")) && (whs.equals("OUED SMAR")))
		   	    
	   	    {
	   	    	System.out.println("magasinier ouad smar");
	   	    	parametreForm.setMagasmar(true)	;
	   	    	trouv=true;
	   	    	parametreForm.setMagaberaki(false);
	   			parametreForm.setMagaregh(false);
	   			
	   			parametreForm.setSuperdist(false);
	   			parametreForm.setAdmin(false);
	   			parametreForm.setMagablida(false);
	   			parametreForm.setMagaconst(false);
	   			parametreForm.setMagaoran(false);
	   			parametreForm.setSupereport(false);
	   			parametreForm.setSuperpre(false);
	   			parametreForm.setSuperpost(false)	;
	   	    }	  
	   	    
	   	 if ((profil.equals("MAGASINIER REGIONAL")) && (whs.equals("REGHAIA")))
		   	    
	   	    {
	   	    	System.out.println("magasinier regh");
	   	    	parametreForm.setMagaregh(true)	;
	   	    	trouv=true;	
	   	    	parametreForm.setMagaberaki(false);
	   			
	   			parametreForm.setMagasmar(false);
	   			parametreForm.setSuperdist(false);
	   			parametreForm.setAdmin(false);
	   			parametreForm.setMagablida(false);
	   			parametreForm.setMagaconst(false);
	   			parametreForm.setMagaoran(false);
	   			parametreForm.setSupereport(false);
	   			parametreForm.setSuperpre(false);
	   			parametreForm.setSuperpost(false)	;
	   	    }
	   	 
	   	if ((profil.equals("MAGASINIER REGIONAL")) && (whs.equals("BLIDA")))
	   	    
   	    {
   	    	System.out.println("magasinier BLIDA");
   	    	parametreForm.setMagablida(true)	;
   	    	trouv=true;	
   	    	parametreForm.setMagaberaki(false);
   			parametreForm.setMagaregh(false);
   			parametreForm.setMagasmar(false);
   			parametreForm.setSuperdist(false);
   			parametreForm.setAdmin(false);
   		
   			parametreForm.setMagaconst(false);
   			parametreForm.setMagaoran(false);
   			parametreForm.setSupereport(false);
   			parametreForm.setSuperpre(false);
   			parametreForm.setSuperpost(false)	;
   	    }
	   	
	   	
if ((profil.equals("MAGASINIER REGIONAL")) && (whs.equals("CONSTANTINE")))
	   	    
   	    {
   	    	System.out.println("magasinier CONSTANTINE");
   	    	parametreForm.setMagaconst(true)	;
   	    	trouv=true;	
   	    	parametreForm.setMagaberaki(false);
   			parametreForm.setMagaregh(false);
   			parametreForm.setMagasmar(false);
   			parametreForm.setSuperdist(false);
   			parametreForm.setAdmin(false);
   			parametreForm.setMagablida(false);
   			
   			parametreForm.setMagaoran(false);
   			parametreForm.setSupereport(false);
   			parametreForm.setSuperpre(false);
   			parametreForm.setSuperpost(false)	;
   	    }
	 
if ((profil.equals("MAGASINIER REGIONAL")) && (whs.equals("ORAN")))
	    
   {
   	System.out.println("magasinier ORAN");
   	parametreForm.setMagaoran(true)	;
   	trouv=true;	
   	parametreForm.setMagaberaki(false);
	parametreForm.setMagaregh(false);
	parametreForm.setMagasmar(false);
	parametreForm.setSuperdist(false);
	parametreForm.setAdmin(false);
	parametreForm.setMagablida(false);
	parametreForm.setMagaconst(false);
	
	parametreForm.setSupereport(false);
	parametreForm.setSuperpre(false);
	parametreForm.setSuperpost(false)	;
   }


 	if ((profil.equals("SUPERVISEUR REPORTING")) )
	   	    
   	    {
   	    	System.out.println("super reporting");
   	    	parametreForm.setSupereport(true)	;
   	    	trouv=true;	
   	    	parametreForm.setMagaberaki(false);
   			parametreForm.setMagaregh(false);
   			parametreForm.setMagasmar(false);
   			parametreForm.setSuperdist(false);
   			parametreForm.setAdmin(false);
   			parametreForm.setMagablida(false);
   			parametreForm.setMagaconst(false);
   			parametreForm.setMagaoran(false);
   			parametreForm.setSuperpost(false)	;
   			
   			parametreForm.setSuperpre(false);
   	    }
 	
 	

 	if ((profil.equals("SUPERVISEUR DISTRIBUTION")) )
	   	    
   	    {
   	    	System.out.println("super DISTRIBUTION");
   	    	parametreForm.setSuperdist(true)	;
   	    	trouv=true;	
   	    	parametreForm.setMagaberaki(false);
   			parametreForm.setMagaregh(false);
   			parametreForm.setMagasmar(false);
   			
   			parametreForm.setAdmin(false);
   			parametreForm.setMagablida(false);
   			parametreForm.setMagaconst(false);
   			parametreForm.setMagaoran(false);
   			parametreForm.setSupereport(false);
   			parametreForm.setSuperpre(false);
   			parametreForm.setSuperpost(false)	;
   	    }
 	
 	
 	if ((profil.equals("SUPERVISEUR POSTPAID")) )
   	    
	    {
	    	System.out.println("super post");
	    	parametreForm.setSuperpost(true)	;
	    	trouv=true;	
	    	parametreForm.setMagaberaki(false);
			parametreForm.setMagaregh(false);
			parametreForm.setMagasmar(false);
			parametreForm.setSuperdist(false);
			parametreForm.setAdmin(false);
			parametreForm.setMagablida(false);
			parametreForm.setMagaconst(false);
			parametreForm.setMagaoran(false);
			parametreForm.setSupereport(false);
			parametreForm.setSuperpre(false);
	    }
	  
 	
 	if ((profil.equals("SUPERVISEUR PREPAID")))
   	    
    {
    	System.out.println("super pre");
    	parametreForm.setSuperpre(true)	;
    	trouv=true;	
    	parametreForm.setMagaberaki(false);
		parametreForm.setMagaregh(false);
		parametreForm.setMagasmar(false);
		parametreForm.setSuperdist(false);
		parametreForm.setAdmin(false);
		parametreForm.setMagablida(false);
		parametreForm.setMagaconst(false);
		parametreForm.setMagaoran(false);
		parametreForm.setSupereport(false);
		parametreForm.setSuperpost(false)	;
		
    }
 	
if ((profil.equals("ADMINISTRATEUR")) )
   	    
    {
    	System.out.println("adminis");
    	parametreForm.setAdmin(true)	;
    	trouv=true;	
    	parametreForm.setMagaberaki(false);
		parametreForm.setMagaregh(false);
		parametreForm.setMagasmar(false);
		parametreForm.setSuperdist(false);
		
		parametreForm.setMagablida(false);
		parametreForm.setMagaconst(false);
		parametreForm.setMagaoran(false);
		parametreForm.setSupereport(false);
		parametreForm.setSuperpre(false);
		parametreForm.setSuperpost(false)	;
    }
}

		
		
}

catch (Exception e){
	
	     		System.out.println(" l'acteur n'exist pas ");
	     		
	     		
	     	}


if (trouv==false){
	System.out.println(" l'acteur n'exist pas ");
parametreForm.setHiddenTest("no user");



parametreForm.setMagaberaki(false);
parametreForm.setMagaregh(false);
parametreForm.setMagasmar(false);
parametreForm.setSuperdist(false);
parametreForm.setAdmin(false);
parametreForm.setMagablida(false);
parametreForm.setMagaconst(false);
parametreForm.setMagaoran(false);
parametreForm.setSupereport(false);
parametreForm.setSuperpre(false);

parametreForm.setSuperpost(false)	;
}	
		return mapping.findForward("modif");
	}
	
	
	
	



	public ActionForward modifier(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException,IOException, ServletException  {
		ParametreForm parametreForm = (ParametreForm) form;
		
		System.out.println("je suis ds modif de parametre");
		return mapping.findForward("autosorti");	
	
	}
	
	
	public ActionForward popup(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException,IOException, ServletException  {
		ParametreForm parametreForm = (ParametreForm) form;
		
		System.out.println("je suis ds popup de parametre");
		return mapping.findForward("reserv");	
	
	}

}