/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yourcompany.struts.UtilClass.Connexion;
import com.yourcompany.struts.form.RecheditForm;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 08-19-2008
 * 
 * XDoclet definition:
 * @struts.action path="/rechedit" name="recheditForm" scope="request" validate="true"
 * @struts.action-forward name="rechedit" path="/forms/rechedit.jsp"
 */
public class RecheditAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RecheditForm recheditForm = (RecheditForm) form;// TODO Auto-generated method stub
	
		//Connection con = null;
		Statement st,st1,st2,st3 = null;
		ResultSet rs,rs1,rs2,rs3 = null;
		String four,mag,type,resp;
		List listFournisseur= new ArrayList() ;
		List listWarehouse= new ArrayList() ;
		List typeTrans= new ArrayList() ;
		List nomResp= new ArrayList() ;
		
		
		
		Connexion connexion=new Connexion();
		Connection con=connexion.createConnection(request);
	/*	
	try{
	 
	    st = con.createStatement();
		st1 = con.createStatement();
		st2=con.createStatement();
		st3=con.createStatement();
		//rs = st.executeQuery("select DEST_NOM from GSS_DESTINATAIRE where DEST_TYPE ='fournisseur'");
		rs1 = st1.executeQuery("select whs_adresse from gss_warehouse where whs_status='A'");
		rs2=st2.executeQuery("select trans_type_libelle from gss_transaction_type");
		rs3=st3.executeQuery("select act_name from gss_actor where act_status='A'");
		
     	
     	while (rs1.next())
    	{
    		    		    		
     	mag = rs1.getString(1).trim();
    	//System.out.println(four);
     	listWarehouse.add(mag);
    	    			    		
    	}
     	recheditForm.setNomWarehouse(listWarehouse);
     	
     	System.out.println(listWarehouse);
		
		while (rs2.next())
    	{
    		    		    		
		type = rs2.getString(1).trim();
    	//System.out.println(four);
		typeTrans.add(type);
     	    	    			    		
    	}
		System.out.println(typeTrans);
		recheditForm.setTypeTrans(typeTrans);
		
		while (rs3.next())
    	{
    		    		    		
		resp = rs3.getString(1).trim();
    	//System.out.println(four);
		nomResp.add(resp);
     	    	    			    		
    	}
		recheditForm.setNomResp(nomResp);
	    
	}
	
	catch(Exception e)
    
    {
     
  System.out.println ("requete echec");
  
  }
	*/  
		recheditForm.setHiddenTest("");
		System.out.println ("je suis ds rechedit"); 
		
		return mapping.findForward("rech");
	}
}